# Generated by Django 5.1.6 on 2026-05-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, unique=True)),
                ('nepali_translation', models.CharField(max_length=255)),
            ],
        ),
    ]
